config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get 'about' => 'static_pages#about', as: 'about'
  get 'contact' => 'static_pages#contact', as: 'contact'
  get 'search' => 'searches#search', as: 'search'
  get 'auth' => 'auth#root', as: 'auth'
 

  resources :entries, only: [:show, :update, :destroy] do
    member do
      get 'facebook'
      get 'twitter'
    end
  end
  resources :categories, only: [:show, :update, :destroy]

  scope :auth do
    resource :sessions, only: [:destroy, :new, :create]
    resources :categories, except: [:show]
    resources :entries, except: [:show]
    resources :media
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  extend FriendlyId

  scope :contains, -> (title) { where('entries.published = ? and LOWER(entries.title) LIKE ?', true, "%#{title.downcase}%") }

  before_validation {
    self.tag = tag.downcase
  }

  friendly_id :title, use: [:slugged, :finders]

  has_and_belongs_to_many :categories, dependent: :destroy

  belongs_to :author

  validates :title, presence: true
  validates :tag, presence: true
  validates :content, presence: true
  validates :clicks, numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  include SessionsHelper
  before_action :authenticate_author, expect: [:show, :facebook, :twitter]
  before_action :set_entry, only: [:show, :edit, :update, :destroy, :facebook, :twitter]
  layout "auth", except: :show
  after_action :save_clicks, only: [:facebook, :twitter]
  
  def show
    if @entry.published?
      @entry.clicks = @entry.clicks + 1
      @entry.save
    else
      render_404
    end
  end

  def destroy
    @entry.destroy
    flash[:success] = "Youu have successfully destroyed an entry!"
    redirect_to entries_path
  end

  def edit
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      flash[:success] = "You have successfully created an entry!"
      redirect_to entries_path
    else
      flash.now[:danger] = "Some errors"
      render action: :new
    end
  end

  def update
    @entry.update(entry_params)
    redirect_to entries_path
  end

  def index
    @entries = Entry.all
  end

  def new
    @entry = Entry.new
  end

  def facebook
    @entry.facebook = @entry.facebook + 1
    redirect_to @entry
  end

  def twitter
    @entry.twitter = @entry.twitter + 1
    redirect_to @entry
  end

  private
    def set_entry
      begin
        @entry = Entry.friendly.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        render_404
      end
    end

    def save_clicks
      if @entry.published?
        @entry.save
      else
        render_404
      end
    end

    def entry_params
      params.require(:entry).permit(:title, :tag, :content, :published, :category_ids => [])      
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <%= render 'shared/errors_messages', object: f.object %>
  <div class="box-body">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :tag %>
      <%= f.text_field :tag, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control wysihtml5' %>
    </div>
    <div class="form-group">
      <%= f.label :categories %>
      <%= f.select :category_ids, Category.all.collect{ |x| [x.name, x.id]},{}, {multiple: true, class: 'form-control'} %>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :published %>
        Published
      </label>
    </div>
  </div>
  <div class="box-footer">
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/entries/edit.html.erb
<% provide(:title, "Edit - Categories") %>
<section class="content-header">
  <h1>
    Edit entry
    <small>Overview</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to auth_path do %>
        <i class="fa fa-dashboard"></i>
        Home
      <% end %>
    </li>
    <li>
      <%= link_to 'Entries', entries_path %>
    </li>
    <li class="active">Edit</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/entries/index.html.erb
<% provide(:title, "Entries") %>
<section class="content-header">
  <h1>
    Entries
    <small>Overview</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to auth_path do %>
        <i class="fa fa-dashboard"></i>
        Home
      <% end %>
    </li>
    <li class="active">Entries</li>
  </ol>
</section>
<section class="content">
  <%= render 'shared/flash_messages' %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Overview</h3>
          <div class="box-tools">
            <%= link_to 'New', new_entry_path, class: 'btn btn-default pull-right' %>
          </div>
        </div>
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>Title</th>
              <th>Content</th>
              <th>Categories</th>
              <th>Published</th>
              <th>Date created</th>
              <th>Clicks</th>
              <th>Visits - Facebook</th>
              <th>Visits - Twitter</th>
              <th>Options</th>
            </tr>
            <% @entries.each do |entry| %>
              <tr>
                <td><%= entry.title %></td>
                <td><%= truncate(entry.content) %></td>
                <td>
                  <ul>
                    <% entry.categories.each do |category| %>
                      <li><%= category.name %></li>
                    <% end %>
                  </ul>
                <td><%= entry.published %></td>
                <td><%= entry.created_at.strftime("%d/%m/%Y") %></td>
                <td><%= entry.clicks %></td>
                <td><%= entry.facebook %></td>
                <td><%= entry.twitter %></td>
                <td><%= link_to 'Show', entry, target: '_blank' %> | <%= link_to 'Edit', edit_entry_path(entry) %> | <%= link_to 'Delete', entry, method: :delete %></td>
              <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/entries/new.html.erb
<% provide(:title, "New - Entries") %>
<section class="content-header">
  <h1>
    Entries
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <a href="#">
        <i class="fa fa-dashboard"></i>
        Home
      </a>
    </li>
    <li>
      <%= link_to 'Entries', entries_path %>
    </li>
    <li class="active">New</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title">New entry</h3>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/entries/show.html.erb
<% provide(:title, @entry.title) %>
<% provide(:description, truncate(@entry.content)) %>
<% provide(:keywords, @entry.tag) %>
<h2>
  <%= @entry.title %>
</h2>
<hr/>
<p>
  <span class="glyphicon glyphicon-time"></span>
  Posted on <%= @entry.created_at.strftime("%B %e, %Y at %R") %>
</p>
<hr/>
<p>
  <%= @entry.content.html_safe %>
</p>
<hr/>
<div id="disqus_thread"></div>
<noscript>
  Please enable JavaScript to view the\
  <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>
<a class="dsq-brlink" href="http://disqus.com">comments powered by Disqus</a>