config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get 'about' => 'static_pages#about', as: 'about'
  get 'contact' => 'static_pages#contact', as: 'contact'
  get 'search' => 'searches#search', as: 'search'
  get 'auth' => 'auth#root', as: 'auth'
 

  resources :entries, only: [:show, :update, :destroy] do
    member do
      get 'facebook'
      get 'twitter'
    end
  end
  resources :categories, only: [:show, :update, :destroy]

  scope :auth do
    resource :sessions, only: [:destroy, :new, :create]
    resources :categories, except: [:show]
    resources :entries, except: [:show]
    resources :media
  end

end

app/views/shared/_entries.html.erb
<% @entries.each do |entry| %>
  <h2>
    <%= link_to entry.title, entry %>
  </h2>
  <span class="glyphicon glyphicon-time"></span>
  Posted on <%= entry.created_at.strftime("%B %e, %Y at %R") %>
  <hr/>
<% end %>

app/views/shared/_errors_messages.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-xs-5 col-xs-offset-3">
      <div class="box box-solid box-danger">
        <div class="box-header">
          <h3 class="box-title">Errors</h3>
        </div>
        <div class="box-body">
          The form contains <%= pluralize(object.errors.count, "error") %>
          <ul>
            <% object.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <div class="row">
    <div class="col-xs-12">
      <% flash.each do |k,v| %>
        <div class="alert-<%= k %> alert alert-dismissable">
          <%= v %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Dennis Tusk</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'about', about_path %>
        </li>
        <li>
          <%= link_to 'contact', contact_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>