config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get 'about' => 'static_pages#about', as: 'about'
  get 'contact' => 'static_pages#contact', as: 'contact'
  get 'search' => 'searches#search', as: 'search'
  get 'auth' => 'auth#root', as: 'auth'
 

  resources :entries, only: [:show, :update, :destroy] do
    member do
      get 'facebook'
      get 'twitter'
    end
  end
  resources :categories, only: [:show, :update, :destroy]

  scope :auth do
    resource :sessions, only: [:destroy, :new, :create]
    resources :categories, except: [:show]
    resources :entries, except: [:show]
    resources :media
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  extend FriendlyId

  friendly_id :name, use: [:slugged, :finders]

  has_and_belongs_to_many :entries


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  include SessionsHelper

  before_action :authenticate_author, except: [:show]
  before_action :set_category, only: [:show, :edit, :destroy, :update]
  layout "auth", except: :show

  def show
    @entries = @category.entries.where(published: true)
    if page_param = params[:page]
      @entries = @entries.page(page_param)
    else
      @entries = @entries.page(@entries.count / Kaminari.config.default_per_page)
    end
  end

  def index
    @categories = Category.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "You have successfully created a category"
    else
      flash[:danger] = "Some errors"
    end
    redirect_to :categories
  end

  def new
    @category = Category.new
  end

  def destroy
    if @category.destroy
      flash[:success] = "You have successfully destroyed a category"
    else
      flash[:danger] = "Some errors"
    end
    redirect_to :categories
  end

  def edit
  end

  def update
    @category.update(category_params)
    flash[:success] = "You have sucessfully updated a category"
    redirect_to categories_path
  end

  private

    def set_category
      begin
        @category = Category.friendly.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        render_404
      end
    end

    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= render 'shared/errors_messages', object: f.object %>
  <div class="box-body">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <div class="box-footer">
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%- provide(:title, "Edit - Categories") %>
<section class="content-header">
  <h1>
    Edit category
    <small>Overview</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to auth_path do %>
        <i class="fa fa-dashboard"></i>
        Home
      <% end %>
    </li>
    <li>
      <%= link_to 'Categories', categories_path %>
    </li>
    <li class="active">Edit</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/categories/index.html.erb
<% provide(:title, "Categories") %>
<section class="content-header">
  <h1>
    Categories
    <small>Overview</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to auth_path do %>
        <i class="fa fa-dashboard"></i>Home
      <% end %>
    </li>
    <li class="active">Categories</li>
  </ol>
</section>
<section class="content">
  <%= render 'shared/flash_messages' %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title"> Overview</h3>
          <div class="box-tools">
            <%= link_to 'New', new_category_path, class: 'btn btn-default pull-right' %>
          </div>
        </div>
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Options</th>
            </tr>
              <% @categories.each do |category| %>
                <tr>
                  <td><%= category.name %></td>
                  <td><%= truncate(category.description) %></td>
                  <td><%= link_to 'Show', category, target: "_blank" %> | 
                    <%= link_to 'Edit', edit_category_path(category) %> | <%= link_to 'Delete', category, method: :delete %>
                  </td>
                </tr>
              <% end %>
              </table>
            </div>
          </div>
        </div>
</section>

app/views/categories/new.html.erb
<% provide(:title, "New - Categories") %>
<section class="content-header">
  <h1>
    Categories
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <a href="#">
        <i class="fa fa-dashboard"></i>
        Home
      </a>
    </li>
    <li>
      <%= link_to 'Categories', categories_path %>
    </li>
    <li class="active">New</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title">New category</h3>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/categories/show.html.erb
<% provide(:title, "#{@category.name} - Category") %>
<% provide(:keywords, "#{@category.name} - Category") %>
<% provide(:description, "#{@category.description} - Category") %>
<h2>Category: <%= @category.name %></h2>
<hr/>
<% unless @entries.empty? %>
  <%= render 'shared/entries' %>
<% else %>
  No entries available
<% end %>
<!-- Pager
-->
<ul class="pager">
  <li class="previous">
    <%= link_to_next_page @entries, '&larr; Newer'.html_safe %>
  </li>
  <li class="next">
    <%= link_to_previous_page @entries, 'Older &rarr;'.html_safe %>
  </li>
</ul>