config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get 'about' => 'static_pages#about', as: 'about'
  get 'contact' => 'static_pages#contact', as: 'contact'
  get 'search' => 'searches#search', as: 'search'
  get 'auth' => 'auth#root', as: 'auth'
 

  resources :entries, only: [:show, :update, :destroy] do
    member do
      get 'facebook'
      get 'twitter'
    end
  end
  resources :categories, only: [:show, :update, :destroy]

  scope :auth do
    resource :sessions, only: [:destroy, :new, :create]
    resources :categories, except: [:show]
    resources :entries, except: [:show]
    resources :media
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="<%= yield :description %>" name="description"/>
    <meta content="<%= yield :keywords %>" name="keywords"/>
    <meta content="Dennis Tusk" name="author"/>
    <title><%= yield :title %> - Dennis Tusk</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag    'application/application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    -->
  </head>
  <body>
    <%= render 'shared/nav' %>
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <%= yield %>
        </div>
        <div class="col-md-4">
          <div class="well">
            <h4>Blog Search</h4>
            <%= form_tag :search, url: search_path, method: :get do %>
              <div class="input-group">
                <%= text_field_tag :query, nil, class: 'form-control' %>
                <span class="input-group-btn">
                  <%= button_tag nil, name: nil, class: 'btn btn-default' do %>
                    <span class="glyphicon glyphicon-search"></span>
                  <% end %>
                </span>
              </div>
            <% end %>
          </div>
          <div class="well">
          <% unless @categories.empty? %>
            <h4>Blog Categories</h4>
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled">
                  <% @categories.each do |category| %>
                    <li>
                      <%= link_to category.name, category, data: {toggle: "tooltip", placement: 'right'}, title: category.description %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <hr/>
      <!-- Footer
      -->
      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p>Copyright &copy; Dennis Tusk 2014</p>
          </div>
          <!-- /.col-lg-12
          -->
        </div>
        <!-- /.row
        -->
      </footer>
    </div>
    <!-- /.container
    -->
    <%= javascript_include_tag 'application/application', 'data-turbolinks-track' => true %>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title><%= yield :title %> - Dashboard - Dennis Tusk</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="//code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag 'auth/auth', media: 'all', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file://
    -->
    <!--[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    -->
  </head>
  <body class="skin-black">
    <!-- header logo: style can be found in header.less
    -->
    <header class="header">
      <%= link_to auth_path, class: 'logo' do %>
        Dennis Tusk
      <% end %>
      <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button
        -->
        <a class="navbar-btn sidebar-toggle" data-toggle="offcanvas" href="#" role="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <div class="navbar-right">
          <ul class="nav navbar-nav">
            <li class="dropdown user user-menu">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="glyphicon glyphicon-user"></i>
                <span>
                  <%= current_author.full_name %>
                  <i class="caret"></i>
                </span>
              </a>
              <ul class="dropdown-menu">
                <!-- User image
                -->
                <li class="user-header bg-light-blue">
                  <p>
                    <%= current_author.full_name %>
                  </p>
                </li>
                <!-- Menu Footer
                -->
                <li class="user-footer">
                  <div class="pull-left">
                    <a class="btn btn-default btn-flat" href="#">Profile</a>
                  </div>
                  <div class="pull-right">
                    <%= link_to 'Sign out', {controller: 'sessions', action: 'destroy'}, class: 'btn btn-default btn-flat', method: :delete %>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <div class="wrapper row-offcanvas row-offcanvas-left">
      <!-- Left side column. contains the logo and sidebar
      -->
      <aside class="left-side sidebar-offcanvas">
        <!-- sidebar: style can be found in sidebar.less
        -->
        <section class="sidebar">
          <!-- Sidebar user panel
          -->
          <!-- search form
          -->
          <form action="#" class="sidebar-form" method="get">
            <div class="input-group">
              <input class="form-control" name="q" placeholder="Search..." type="text">/</input>
              <span class="input-group-btn">
                <button class="btn btn-flat" id="search-btn" name="seach" type="submit">
                  <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
          </form>
          <!-- /.search form
          -->
          <!-- sidebar menu: : style can be found in sidebar.less
          -->
          <ul class="sidebar-menu">
            <li>
              <%= link_to auth_path do %>
                <i class="fa fa-dashboard"></i>
                <span>Dashboard</span>
              <% end %>
            </li>
            <li>
              <%= link_to entries_path do %>
                <i class="fa fa-th"></i>
                <span>Entries</span>
              <% end %>
            </li>
            <li>
              <%= link_to categories_path do %>
                <i class="fa fa-folder"></i>
                <span>Categories</span>
              <% end %>
            </li>
            <li>
              <%= link_to media_path do %>
                <i class="fa fa-image"></i>
                <span>Media</span>
              <% end %>
            </li>
          </ul>
        </section>
        <!-- /.sidebar
        -->
      </aside>
      <!-- Right side column. Contains the navbar and content of the page
      -->
      <aside class="right-side">
        <%= yield %>
      </aside>
    </div>

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
    <%= javascript_include_tag 'auth/auth' %>
  </body>
</html>

app/views/layouts/sign_in.html.erb
<!doctype html>
<html class="bg-black">
  <head>
    <meta charset="UTF-8"/>
    <title><%= yield :title %></title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"/>
    <%= stylesheet_link_tag 'auth/auth' %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    -->
  </head>
  <body class="bg-black">
    <div class="form-box" id="login-box">
      <div class="header">Sign In</div>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'auth/auth', "data-turbolinks-track" => true %>
  </body>
</html>